---
Test
---
Feature: Multiplication - runtime exception
Feature description

  Scenario: 2 squared

    Given a variable x with value 2
    When I multiply x by 2
    Then throw exception
    Then x should equal 4